// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pykwsfoldzamvivlobop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5a3dzZm9sZHphbXZpdmxvYm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjUxNjEsImV4cCI6MjA2NTA0MTE2MX0.1k2pFdHDLHCNPVXqS44HvGCWTag3sX8bYGYjXVxbJb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);